# shellcheck shell=bash

alias gall='ga && gcu && gpom'
alias grh='git reset --hard'
alias gclean='git reset --hard && git clean -dfx'
alias gm='git merge'
alias get='git'
alias gs='git status'
alias gss='git status -s'
alias gpl='git pull'
alias gpr='git pull --rebase'
alias gpp='git pull && git push'
alias gup='git fetch && git rebase'
alias gps='git push'
alias gpo='git push origin'
alias gdv='git diff -w "$@" | vim -R -'

alias gc='git commit -v'
alias gca='git commit -v -a'
alias gci='git commit --interactive'
alias gb='git branch -a'
alias gba='git --no-pager branch -a'
alias gcount='git shortlog -sn'
alias gcp='git cherry-pick'
alias gco='git checkout'
alias gexport='git archive --format zip --output'
alias gdel='git branch -D'
alias gmu='git fetch origin -v; git fetch upstream -v; git merge upstream/master'
alias gll='git log --graph --pretty=oneline --abbrev-commit'
alias gg="git log --graph --pretty=format:'%h -%d %s (%cr)' --abbrev-commit --date=relative"
alias ggs='gg --stat'
alias gsl='git shortlog -sn'
alias gw='git whatchanged'
alias gt='git tag'
alias gta='git tag -a'
alias gtd='git tag -d'
alias gtl='git tag -l'

alias grv='git remote -v'
alias grmv='git remote rename'
alias grrm='git remote remove'
alias grset='git remote set-url'
alias grup='git remote update'
alias grbi='git rebase -i'
alias grbc='git rebase --continue'
alias grba='git rebase --abort'
alias gbr='git branch --remote'
alias gcl='git config --list'
alias glg='git log --stat --max-count=10'
alias glgg='git log --graph --max-count=10'
alias glgga='git log --graph --decorate --all'
alias glo='git log --oneline --decorate --color'
alias glog='git log --oneline --decorate --color --graph'
alias gsts='git stash show --text'
alias gstl='git --no-pager stash list'
alias gsta='git stash'
alias gstp='git stash pop'
alias gstd='git stash drop'

alias gfp='git fetch --prune'
alias gda='git diff'
alias gdc='git diff ^HEAD'
alias ga='git add .'
alias gdt='git difftool -y'

alias gplom='git pull origin master'
alias gphom='git push origin master'
alias gplod='git pull origin develop'
alias gphod='git push origin develop'

alias gcm='git checkout master'
alias gcd='git checkout develop'
alias gl='git log --graph --date=short --decorate=short --pretty=format:'\''%Cgreen%h %Creset%cd %Cblue%cn %Cred%d %Creset%s'\'''
alias gf='git fetch --all'
alias gconf='git config --list'
alias gas='git am --show-current-patch'
